name: Publish Python Executables to GitHub Release

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: snake-linux
          - os: windows-latest
            artifact_name: snake-windows
            additional_packages: windows-curses

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"

    - name: Install requirements
      run: |
        pip install pygame pyinstaller ${{ matrix.additional_packages || '' }}

    - name: Build executable
      run: |
        pyinstaller --onefile main.py --noconsole -y

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-linux
          path: dist/linux/
          
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-windows
          path: dist/windows/
          
      - name: Create GitHub Release
        run: |
          gh release create v1.1.0 \
            ./dist/linux/main --title "Linux Executable" --notes "Automated release of Linux executable." \
            ./dist/windows/main.exe --title "Windows Executable" --notes "Automated release of Windows executable."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
