name: Publish Python Executables to GitHub Release

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"

    - name: Install requirements
      run: |
        pip install pygame pyinstaller

    - name: Build Linux executable
      run: |
        pyinstaller --onefile main.py --noconsole -y

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-linux
        path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"

    - name: Install requirements
      run: |
        pip install pygame pyinstaller windows-curses

    - name: Build Windows executable
      run: |
        pyinstaller --onefile main.py --noconsole -y

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-windows
        path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"

    - name: Install requirements
      run: |
        pip install pygame pyinstaller

    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed main.py -y

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-macos
        path: dist/

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux build artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-linux
          path: dist/linux/
          
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-windows
          path: dist/windows/

      - name: Download macOS build artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-macos
          path: dist/macos/
          
      - name: Create GitHub Release
        run: |
          gh release create v1.1.0 \
            ./dist/linux/main --title "Linux Executable" --notes "Automated release of Linux executable." \
            ./dist/windows/main.exe --title "Windows Executable" --notes "Automated release of Windows executable." \
            ./dist/macos/main.app --title "macOS Executable" --notes "Automated release of macOS executable."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
